### ISSUE TITLE
NameError: name '..................................' is not defined

### ISSUE THREAD

**Issue by thc2018** [yandex/yandex_tracker_client#2]
from yandex_tracker_client import TrackerClient
client = TrackerClient(token=.................., org_id=XXXXX)
--------------------------------------------------------------
python3 ya_get.py
Traceback (most recent call last):
  File "ya_get.py", line 2, in <module>
    client = TrackerClient(token=.........................., org_id=XXXXX)
NameError: name '....................' is not defined

Python 3.7.3

**Comment by Smosker** [comment]
hello! Can you please provide full sample with full traceback?
Tried lastest version on 3.7.5
```
from yandex_tracker_client import TrackerClient
client = TrackerClient(token='smth', org_id='1111')  # -> no error
```
got no error

**Comment by thc2018** [comment]
The problem was "'" is missing in my case

Thank you!
